### ISSUE TITLE
Build webApps

### ISSUE THREAD

**Issue by satakagi** [cytan299/tribahtinov#1]
Hi, I just ported Tri-Bahtinov mask drawings generator to webApps.
 
http://svg2.mbsrv.net/astro/Tri-Bahtinov.html

**Comment by cytan299** [comment]
Hi Satoru,   Thanks for doing this! Wow! Fantastic! You might want to announce this on cloudynights and astronomyforum. 
cytan

**Comment by cytan299** [comment]
I've added links to your webapp in both the README.md and wiki.
