### ISSUE TITLE
Term Airy Disk is used incorrectly in the illustrations

### ISSUE THREAD

**Issue by mitchmitchell** [cytan299/tribahtinov#7]
The images labeled as Airy Disks in the Results section of the readme are actually out of focus star images, the Airy Disk pattern is only visible with an in-focus star image.   See: https://en.wikipedia.org/wiki/Airy_disk and the Third Step in Therry Legault's description of collimation: http://www.astrophoto.fr/collim.html

**Comment by cytan299** [comment]
Hi Mitch,
  Thanks for pointing it out! I'll change it over the weekend.

cytan
