### ISSUE TITLE
tri-bahtinov mask to collimate HyperStar lens

### ISSUE THREAD

**Issue by skyjak** [cytan299/tribahtinov#8]
Hi, I was wondering if in order to collimate a HyperStar lens the tri-Bahtinov mask should be made for the shorter focal length (f/2) instead of the regular one for f/10?  I guess the number of slots optimal for f/2 will be different than for f/10, correct?  If this is so, do you know who can 3D-print this f/2 TriBahtinov mask? Thanks!

**Comment by cytan299** [comment]
Sorry, I have no idea. I don't have hyperstar. I'd suggest asking on the Cats/Casses forum on cloudynights. People there have used the TriBahtinov for collimating f/2 systems.

**Comment by skyjak** [comment]
OK, thanks.
